name: QMK

on:
  - push

env:
  KEYBOARD: fortitude60
  KEYMAP: via

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone qmk/qmk_firmware
      uses: actions/checkout@v2
      with:
        repository: 'qmk/qmk_firmware'
        submodules: true

    - name: Install dependencies
      run: ./util/qmk_install.sh

    - name: Compile
      run: ./bin/qmk compile -kb $KEYBOARD -km $KEYMAP

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ./.build/*.hex
